[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0", features = ["api-all"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
dotenvy = "0.15"
dotenv = "0.15"
warp = { version = "0.3", features = ["tls"] }
open = "5.0.0"
ignore = "0.4"
rayon = "1.5"
dirs = "3.0"
threadpool = "1.8"
crossbeam-channel = "0.5"
num_cpus = "1.14"
tauri-plugin-localhost = "0.1.0"
mime_guess = "2.0"
oneshot = "0.1.8"
tokio-util = "0.6"
actix-web = "4.0"
actix-files = { version = "0.6.0-beta.16" }
base64 = "0.13"
actix-cors = "0.6"
thiserror = "1.0"
<<<<<<< HEAD
urlencoding = "2.1.3"
octocrab = "0.10.0"
futures = "0.3"
anyhow = "1.0"
async-std = "1.10"
async-recursion = "0.1.0"
lru-cache = "0.1.2"
=======
urlencoding =  "2.1.3"
serde_qs = "0.12.0"
>>>>>>> 03781c1 (auth window redesign)


[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
