"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";

const Hero = () => {
  return (
    <div className="z-10 flex flex-row items-center justify-center md:mt-72 mt-44">
      <div className="flex flex-col items-center justify-center gap-y-2">
        <span className="text-5xl text-center px-3 md:text-[5rem] font-semibold drop-shadow-2xl">
          Search everything, <br className="md:block hidden" />
          <span className="bg-gradient-to-r from-[#DE2D24] to-[#E85311] text-transparent bg-clip-text">
            find anything.
          </span>
        </span>{" "}
        {/* <span className="text-red-400 text-center font-semibold md:mt-10 text-5xl md:text-[5rem] drop-shadow-2xl">
          for everyone
        </span> */}
        <span className="w-[300px] md:w-[500px] text-sm md:text-base text-muted-foreground font-semibold text-center mt-14 drop-shadow-2xl">
          {/* Autogenerated Jupyter Notebooks, Datasets, SSH, and Tunneling. */}
        </span>
        {/* <span className="text-sm md:text-base text-center my-[0.1rem] text-muted-foreground font-semibold drop-shadow-2xl">
          FROM IDEA TO MODEL IN JUST{" "}
          <i className="italic">FOUR COMMANDS</i>.
        </span> */}
      </div>
    </div>
  );
};

export default Hero;
